# Basic Linear Regression on Concrete Dataset
---
In concrete dataset we are finding linear relationship between input vraiables and target variables..
Here below we are importing pytorch to convert into matrix form for processing data
And importing pandas for reading the csv file

# 

In [13]:
import torch
import pandas as pd
import numpy as np

- Selecting 500 rows for training the data
- Splitting the dataset into two

In [14]:
dataset = pd.read_csv("./Concrete.csv")[:500]
data1= dataset[['cement','slag','flyash','water','superplasticizer','coarseaggregate','fineaggregate','age']]
data2 = dataset['csMPa']

We can't directly convert the data into tensor arrays .So we are firstly,
converting the dataset into Numpy array.Then we convert into tensor arrays

In [15]:
dataset1=np.array(data1)
dataset2=np.array(data2).reshape(-1,1)
feature=torch.tensor(dataset1,dtype=torch.float32)
labels=torch.tensor(dataset2,dtype=torch.float32)

We are using the linear model using the function **Linear** from **torch.nn** class.
- (8,1) indicates number of input variables i.e, features and number of targets.

In [16]:
model = torch.nn.Linear(8,1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0506, -0.1082, -0.3471, -0.3114,  0.1355,  0.1758, -0.2127, -0.1315]],
       requires_grad=True)
Parameter containing:
tensor([0.2808], requires_grad=True)


In [17]:
preds = model(feature)
print(preds)

tensor([[ -41.7151],
        [ -39.0776],
        [-100.9044],
        [-113.3993],
        [-134.7393],
        [ -86.9453],
        [-110.6638],
        [ -66.3396],
        [ -78.7907],
        [ -60.8686],
        [ -99.2273],
        [ -91.0727],
        [ -95.4334],
        [ -91.3221],
        [ -76.6023],
        [ -80.3801],
        [ -88.5543],
        [-118.7382],
        [ -74.4942],
        [ -80.8605],
        [ -83.5960],
        [ -80.3997],
        [ -77.1116],
        [-100.3917],
        [-116.5498],
        [-104.0548],
        [ -98.1689],
        [ -94.4059],
        [ -63.6041],
        [ -58.1065],
        [-120.9266],
        [-123.1150],
        [-111.0647],
        [ -92.6979],
        [-127.4917],
        [-106.3753],
        [ -74.5460],
        [ -77.2297],
        [ -69.0232],
        [ -94.5380],
        [ -82.5685],
        [-107.9283],
        [-118.8703],
        [ -92.2175],
        [ -71.7587],
        [ -60.8420],
        [ -65.0524],
        [ -86

Finding mean square loss between targets/labels and predicted values

In [18]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)

- loss.backward() function finds the gradient 
- model.weights.grad means the gradient for weights
- model.bias.grad means the gradient for bias

In [19]:
loss.backward()
print(model.weight.grad)
print(model.bias.grad)

tensor([[ -82855.3438,  -18524.4219,  -19147.0469,  -48326.0859,   -2532.9023,
         -273598.3438, -220962.6875,  -16361.3682]])
tensor([-280.3467])


- torch.optim will hold the current state and will update the parameters based on the computed gradients.
 

- To construct an Optimizer you have to give it an iterable containing the parameters (all should be Variable s) to optimize. Then, you can specify optimizer-specific options such as the learning rate

- optimizers implement a step() method, that updates the parameters.

- Zero_grad() function sets the gradients of all optimized values to zero

In [20]:
optimize = torch.optim.SGD(model.parameters(), lr=0.00000001)

optimize.step()
optimize.zero_grad()

preds = model(feature)
loss = mse_loss(preds, labels)
print(loss)

tensor(19105.5684, grad_fn=<MseLossBackward0>)


We reduce the loss by varying the epochs value and learning rate

In [21]:
optimize= torch.optim.SGD(model.parameters(), lr=0.0000001)

epochs = 100000
for epoch in range(epochs):
    preds = model(feature)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimize.step()
    optimize.zero_grad()

tensor(347.8519, grad_fn=<MseLossBackward0>)
tensor(253.6053, grad_fn=<MseLossBackward0>)
tensor(213.9779, grad_fn=<MseLossBackward0>)
tensor(189.9368, grad_fn=<MseLossBackward0>)
tensor(173.4416, grad_fn=<MseLossBackward0>)
tensor(161.7378, grad_fn=<MseLossBackward0>)
tensor(153.3505, grad_fn=<MseLossBackward0>)
tensor(147.3132, grad_fn=<MseLossBackward0>)
tensor(142.9527, grad_fn=<MseLossBackward0>)
tensor(139.7927, grad_fn=<MseLossBackward0>)
tensor(137.4944, grad_fn=<MseLossBackward0>)
tensor(135.8161, grad_fn=<MseLossBackward0>)
tensor(134.5854, grad_fn=<MseLossBackward0>)
tensor(133.6788, grad_fn=<MseLossBackward0>)
tensor(133.0076, grad_fn=<MseLossBackward0>)
tensor(132.5081, grad_fn=<MseLossBackward0>)
tensor(132.1343, grad_fn=<MseLossBackward0>)
tensor(131.8530, grad_fn=<MseLossBackward0>)
tensor(131.6400, grad_fn=<MseLossBackward0>)
tensor(131.4777, grad_fn=<MseLossBackward0>)
tensor(131.3533, grad_fn=<MseLossBackward0>)
tensor(131.2574, grad_fn=<MseLossBackward0>)
tensor(131