In [1]:
import torch
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("./Concrete.csv")[:500]
data1= dataset[['cement','slag','flyash','water','superplasticizer','coarseaggregate','fineaggregate','age']]
data2 = dataset['csMPa']

In [3]:
dataset1=np.array(data1)
dataset2=np.array(data2).reshape(-1,1)
feature=torch.tensor(dataset1,dtype=torch.float32)
labels=torch.tensor(dataset2,dtype=torch.float32)

In [4]:
model = torch.nn.Linear(8,1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0082, -0.3020, -0.1251, -0.1982, -0.0502, -0.1805, -0.1054, -0.0891]],
       requires_grad=True)
Parameter containing:
tensor([-0.1406], requires_grad=True)


In [5]:
preds = model(feature)
print(preds)

tensor([[-298.2683],
        [-300.9756],
        [-345.9940],
        [-354.4625],
        [-375.5083],
        [-328.8069],
        [-340.5074],
        [-310.4666],
        [-323.2801],
        [-282.5563],
        [-351.4400],
        [-345.9132],
        [-318.0838],
        [-351.1351],
        [-312.1160],
        [-295.3146],
        [-384.6306],
        [-330.9927],
        [-315.9934],
        [-296.1059],
        [-310.0610],
        [-379.1038],
        [-376.8752],
        [-392.6534],
        [-319.8286],
        [-311.3601],
        [-332.0389],
        [-314.5015],
        [-296.5114],
        [-280.6844],
        [-342.1568],
        [-353.3209],
        [-359.4628],
        [-304.1287],
        [-375.6491],
        [-373.9043],
        [-352.3320],
        [-329.9485],
        [-288.0831],
        [-365.8816],
        [-306.4787],
        [-326.5522],
        [-382.3728],
        [-303.3373],
        [-302.0382],
        [-294.6395],
        [-315.3551],
        [-324

In [6]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)

In [7]:
loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor([[-217875.3125,  -51538.8516,  -49802.9961, -128958.4766,   -6492.9897,
         -733367.6875, -580577.8750,  -41290.1641]])
tensor([-744.8736])


In [8]:
optimize = torch.optim.SGD(model.parameters(), lr=0.00000001)

optimize.step()
optimize.zero_grad()

preds = model(feature)
loss = mse_loss(preds, labels)
print(loss)

tensor(130107.4453, grad_fn=<MseLossBackward0>)


In [9]:
optimize= torch.optim.SGD(model.parameters(), lr=0.0000001)

epochs = 10000
for epoch in range(epochs):
    preds = model(feature)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimize.step()
    optimize.zero_grad()

tensor(248.4416, grad_fn=<MseLossBackward0>)
tensor(188.1981, grad_fn=<MseLossBackward0>)
tensor(169.0212, grad_fn=<MseLossBackward0>)
tensor(157.4355, grad_fn=<MseLossBackward0>)
tensor(149.4635, grad_fn=<MseLossBackward0>)
tensor(143.8651, grad_fn=<MseLossBackward0>)
tensor(139.9209, grad_fn=<MseLossBackward0>)
tensor(137.1404, grad_fn=<MseLossBackward0>)
tensor(135.1797, grad_fn=<MseLossBackward0>)
tensor(133.7971, grad_fn=<MseLossBackward0>)
